# Generated by Django 2.1 on 2018-08-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontonr', models.CharField(max_length=10)),
                ('saldo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Laki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=20)),
                ('nachname', models.CharField(max_length=20)),
                ('konto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.Konto')),
            ],
        ),
        migrations.CreateModel(
            name='Zelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeltnummer', models.IntegerField()),
                ('zeltname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='laki',
            name='zelt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.Zelt'),
        ),
    ]
