# Generated by Django 2.1 on 2018-08-07 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laki',
            name='geburtsdatum',
            field=models.DateField(default=datetime.date(2018, 8, 7)),
        ),
        migrations.AddField(
            model_name='laki',
            name='geschlecht',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='laki',
            name='impfpassVorhanden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laki',
            name='krankenkassenkarteVorhanden',
            field=models.BooleanField(default=False),
        ),
    ]
