# Generated by Django 2.1 on 2018-08-07 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20180807_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laki',
            name='geburtsdatum',
            field=models.DateField(default=datetime.datetime(2018, 8, 7, 19, 14, 23, 641744, tzinfo=utc)),
        ),
    ]
