# Generated by Django 2.1 on 2018-08-07 20:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_auto_20180807_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laki',
            name='geburtsdatum',
            field=models.DateField(default=datetime.datetime(2018, 8, 7, 20, 38, 59, 578383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='zelt',
            name='zeltnummer',
            field=models.CharField(max_length=2),
        ),
    ]
