# Generated by Django 2.1 on 2018-08-08 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_auto_20180807_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laki',
            name='geburtsdatum',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
