# Generated by Django 2.1 on 2018-08-10 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_auto_20180808_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Zeltlager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.IntegerField(default=1900)),
                ('haelfte', models.IntegerField(default=1)),
                ('kasse', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.RenameField(
            model_name='konto',
            old_name='kontonr',
            new_name='kontoNr',
        ),
        migrations.RemoveField(
            model_name='konto',
            name='saldo',
        ),
        migrations.AddField(
            model_name='konto',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='buchung',
            name='konto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.Konto'),
        ),
        migrations.AddField(
            model_name='zelt',
            name='zeltlager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.Zeltlager'),
        ),
    ]
