# Generated by Django 2.1 on 2018-08-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_auto_20180810_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='laki',
            name='handy',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laki',
            name='ort',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laki',
            name='plz',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laki',
            name='strase',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laki',
            name='telefon',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
