# Generated by Django 2.1 on 2018-08-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0007_auto_20180810_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='laki',
            name='arztzettelVorhanden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laki',
            name='elternzettelVorhanden',
            field=models.BooleanField(default=False),
        ),
    ]
