# Generated by Django 2.1 on 2018-08-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_auto_20180810_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laki',
            name='strase',
            field=models.CharField(max_length=30),
        ),
    ]
