# Generated by Django 2.1 on 2018-08-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0009_auto_20180810_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
