# Generated by Django 2.1 on 2018-08-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0010_buchung_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laki',
            name='hinweis',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
