# Generated by Django 2.1 on 2019-03-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0013_laki_privatversichert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laki',
            name='handy',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='laki',
            name='hinweis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='laki',
            name='ort',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='laki',
            name='plz',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='laki',
            name='strase',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='laki',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
