# Generated by Django 2.1 on 2019-03-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0014_auto_20190302_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laki',
            name='handy',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
