# Generated by Django 2.1 on 2019-07-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0017_auto_20190718_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zelt',
            name='zelt_balance',
        ),
        migrations.RemoveField(
            model_name='zeltlager',
            name='lager_balance',
        ),
        migrations.AddField(
            model_name='zelt',
            name='zeltkonto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.Konto'),
        ),
        migrations.AddField(
            model_name='zeltlager',
            name='lagerkonto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.Konto'),
        ),
    ]
