# Generated by Django 2.1 on 2019-07-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0018_auto_20190718_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zelt',
            name='zeltname',
            field=models.CharField(max_length=50),
        ),
    ]
